### ISSUE TITLE
Support dynamic linking with `llvm-sys`

### ISSUE THREAD

**Issue by sanmai-NL** [aya-rs/bpf-linker#149]
Under Alpine Linux, i.e. a target for which static linking is the default, installing `bpf-linker` (without the default features as per the docs), fails unless, for one, `rustc` option `-C target-feature=-crt-static` is set. This because `bpf-linker`'s build uses procedural macros which are incompatible with static linking currently. However, `bpf-linker`s dependency `llvm-sys` has a build script which results in static linking by default:

https://gitlab.com/taricorp/llvm-sys.rs/-/blob/main/README.md?ref_type=heads#cargo-features

> If none are enabled, `force-static` is assumed (matching the behavior of older version of `llvm-sys` that did not support dynamic linking).

## Solution

Please respond to this issue with your analysis of the problem and alternatives/work-arounds. If we agree, I'm ready to submit a PR.

Either support configuring one or more `llvm-sym` linkage modes as a Cargo feature for `bpf-linker`, or perhaps set `prefer-dynamic` or even `force-dynamic` by default, or both.

Note from the previously cited docs:

> Most crates that depend on `llvm-sys` should not automatically enable any of these features, because the appropriateness of any given option usually depends on the configuration of the system on which the library is being compiled.

For example, add this to your `Cargo.toml`.

`Cargo.toml`

```toml
[features]
llvm-sys-force-dynamic = ["llvm-sys/force-dynamic"]
```

**Comment by vadorovsky** [comment]
You can pick the feature of llvm-sys yourself. Doing something like:

```
cargo install bpf-linker --features llvm-sys/force-dynamic
cargo build --features llvm-sys/force-dynamic
```

Should work. There is no reason to enforce any kind of linking in our Cargo.toml.

Our plan is build bpf-linker with statically linked LLVM and publish it as a release artifact. Your idea of putting force-dynamic to Cargo.toml would make it impossible. So let's just let people to pick the linking type whenever they need.

**Comment by alessandrod** [comment]
@vadorovsky for people that prefer to build from source, we should still document the recommended way to make things work on Alpine if our default build instructions don't work

**Comment by sanmai-NL** [comment]
@alessandrod To be clear, these instructions apply regardless of how LLVM is built. Moreover, I noticed there's no musl-compatible GitHub release in this project, so people who prefer to build from source is more like, everyone trying to use this product under Alpine Linux (without additional tweaks).
