### ISSUE TITLE
Add --btf option

### ISSUE THREAD

**Issue by alessandrod** [aya-rs/bpf-linker#176]
Before we merge the fix-di branch into main, we should add a `--btf` cmdline option. Then we should keep stripping debug info in main by default unless `--btf` is passed. This way we give folks an opt-in way to test BTF emission (compile with `-C link-arg=--btf`), without impacting people who don't need BTF.

**Comment by qjerome** [comment]
I can jump on this one if you guys want !

**Comment by alessandrod** [comment]
Sure go for it!
