### ISSUE TITLE
workflows: ensure bpf-linker works for aya integration tests

### ISSUE THREAD

**Issue by ajwerner** [aya-rs/bpf-linker#65]
It'd be nice to know that changes to bpf-linker don't break the aya integration tests.

Locally I find that a recent build of https://github.com/aya-rs/bpf-linker/pull/35 fails to link on many of the tests.

**Comment by alessandrod** [comment]
https://github.com/aya-rs/aya/pull/634 introduces a dependency on the latest bpf-linker which includes this https://github.com/aya-rs/bpf-linker/pull/63

I agree it would be nice if we could somehow reify this dependency in code/something
